repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        stages: [manual]

  - repo: local
    hooks:
      - id: prettier-staged
        name: Prettier Staged
        entry: |
          bash -c '
          if ! command -v git-format-staged &> /dev/null
          then
              npm install -g git-format-staged prettier
          fi
          git-format-staged -f "prettier --ignore-unknown --stdin --stdin-filepath \"$FILENAME\""
          '
        language: system
        files: \.(js|jsx|ts|tsx|json|md|mdx|css|scss|html|yaml|yml)$
