name: Enhancement ✨
description: Suggest an improvement to an existing feature
title: "[Enhancement] "
labels: enhancement
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for this enhancement.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: enhancement-description
    attributes:
      label: Describe the desired enhancement
      description: Explain the functionality you'd like to see improved.
      placeholder: What enhancement would you like to see added?
      validations:
        required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this enhancement enhance your use of the project?
      placeholder: Describe a specific use case or scenario where this enhancement would be beneficial.
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this enhancement bring to the project or community?
      placeholder: Explain the advantages of implementing this enhancement.
  - type: textarea
    id: screenshots
    attributes:
      label: Add Screenshots
      description: If any...
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the level of importance for your suggestion.
      options:
        - High
        - Medium
        - Low
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information (optional)
      description: Provide any relevant details, sketches, or examples to clarify your request.
  - type: checkboxes
    id: terms
    attributes:
      label: Record
      options:
        - label: "I have read the Contributing Guidelines"
          required: true
        - label: "I have starred the repository"
          required: true