name: Translate README

on:
  push:
    branches:
      - main
      - master
      - auto-translation
    paths:
      - "README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages
      - name: Adding README - Chinese Simplified
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
      - name: Adding README - German
        uses: dephraiim/translate-readme@main
        with:
          LANG: de
      - name: Adding README - French
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr
      - name: Adding README - Spanish
        uses: dephraiim/translate-readme@main
        with:
          LANG: es
      - name: Adding README - Japanese
        uses: dephraiim/translate-readme@main
        with:
          LANG: ja
